### ISSUE TITLE
Making the App Responsive and Look Awesome on Mobile Devices

### ISSUE THREAD

**Issue by kenmazaika** [mb-kaizen/1st-project#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by mb-kaizen** [comment]
Hi Ken, I think I got it...

To the head, I added:
    <meta name="viewport" content="width=device-width,initial-scal=1">

It should be updated on GitHub as well. 

Thanks!
Michael

**Comment by kenmazaika** [comment]
Looks very close, Michael!  Looks like you might have a typo on the `initial-scale=1` part, though!

**Comment by mb-kaizen** [comment]
*facepalm

Should be ok now!

Thanks!

**Comment by kenmazaika** [comment]
Looks great.  Thumbs up!
